version: '2.0'
services:
  go-apps:
    image: williamchang80/sea-apd:1.0
    ports:
      - "8090:8090"
      - "8091:8091"
    environment:
      - PG_HOST=103.129.222.233
      - PG_PORT=5432
      - PG_NAME=apd
      - PG_USER=compfest
      - PG_PASSWORD=s34*&apd
      - APP_PORT=8090
      - SWAGGER_PORT=8091
      - SECRET_AUTH_KEY=SeaApd!!
  go-nginx:
    image: williamchang80/nginx-apd:1.0
    ports:
      - "80:80"
    depends_on:
      - go-apps
