version: '2.0'
services:
  web:
    image: williamchang80/sea-apd:1.0
    ports:
      - "8090:8090"
    environment:
      - PG_HOST=103.129.222.233
      - PG_PORT=5432
      - PG_NAME=apd
      - PG_USER=compfest
      - PG_PASSWORD=s34*&apd
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - "web"
