name: Production workflow

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build
        run: go build -v .

  push_to_registry:
    name: Push Image To Registry
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag williamchang80/sea-apd:1.0
      - name: Push the tagged Docker image
        run: docker push williamchang80/sea-apd:1.0
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag williamchang80/sea-apd:latest
      - name: Push the latest Docker image
        run: docker push williamchang80/sea-apd:latest
  
  deploy_to_azure:
    name: Deploy To Azure
    runs-on: ubuntu-latest
    needs: [build, push_to_registry]
    steps:
      - name: Executing remote ssh commands using password and login into dockerhub
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_ADDRESS }}
          username: ${{ secrets.AZURE_USER }}
          password: ${{ secrets.AZURE_PASSWORD }}
          port: 22
          script: |
            sudo su
            sudo chmod 666 /var/run/docker.sock
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Pull image from dockerhub
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_ADDRESS }}
          username: ${{ secrets.AZURE_USER }}
          password: ${{ secrets.AZURE_PASSWORD }}
          port: 22
          script: docker pull williamchang80/sea-apd && docker pull williamchang80/nginx-apd:1.0
      - name: Run docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_ADDRESS }}
          username: ${{ secrets.AZURE_USER }}
          password: ${{ secrets.AZURE_PASSWORD }}
          port: 22
          script: docker-compose up -d   
      
